apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata: 
  name: ingress-deployment
  labels:
    app: ingress-label
spec:
  ingressClassName:  azure-application-gateway                                            #ish se pahle azure k8s cluter jake networking/ jakar ingress-app gateway ko enable krte hai
  rules:
    - host: todoui.techno028.shop
      http:
       paths:
        - backend:                                                                         #ish backend main service deployment ki detail aae hai ya aayegi
           service: 
            name: todo-ui
            port:
             number: 80
          path: /
          pathType: Prefix   
         
